#include <iostream>
#include <fstream>
#include <vector>
#include "TFile.h"
#include "TROOT.h"
#include "TStyle.h"
#include "TMath.h"
#include "TRandom3.h"
#include "TChain.h"
#include "TTree.h"
#include "TH1D.h"
#include "TH2D.h"
#include "TH3D.h"
#include "TCanvas.h"
#include "TLegend.h"  
#include "TLatex.h"
#include "TGraphErrors.h"
#include "TGraphAsymmErrors.h"
#include "TGraph2D.h" 
#include "TVirtualFFT.h"     
#include "TLine.h"    
#include "TMinuit.h"    
#include "TNtuple.h"    
#include <filesystem>
